models/Contact_form.py
from app import db

class Contact_form(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    name = db.Column(db.String(20), nullable=False)
    email = db.Column(db.String(30), nullable=False)
    phone_number = db.Column(db.String(30), nullable=False)
    message = db.Column(db.String(100), nullable=False)
    date = db.Column(db.String(30), nullable=False)

routes/user_bp.py
from flask import Blueprint, render_template, redirect, url_for, flash
from flask_login import login_required, current_user, logout_user
from functools import wraps

user_bp = Blueprint('user_bp', __name__)

from controllers.UserController import home_page, dashboard_details, about_details, post_page, contact_page, single_POST, admin_user_dashboard, all_blogs_details, add_blogs_details, my_blogs_details, update_specific_blog
from controllers.auth_controller import login_check, register_check



@user_bp.route('/')
def home():
    return home_page()


@user_bp.route('/login', methods=["GET", "POST"])
def login():
    validate_data = login_check()
    if not validate_data:
        flash("User Doesn't Exists!!")
    return validate_data


@user_bp.route('/logout')
@login_required
def logout():
    logout_user()
    return redirect(url_for('user_bp.home'))

@user_bp.route('/register', methods=['GET', 'POST'])
def register():
    validate_data = register_check()
    return validate_data


@user_bp.route('/dashboard')
@login_required
def dashboard():
    dashboard  = dashboard_details()
    return dashboard


# NORMAL PAGES ROUTE STARTS HERE

@user_bp.route('/about')
def about():
    return about_details()

@user_bp.route('/post')
def posts():
    return post_page()


@user_bp.route('/contact-us' , methods=["GET","POST"])
def contact_us():
    return contact_page()


@user_bp.route('/post/<string:post_slug>', methods=["GET","POST"])
def sinlge_post(post_slug):
    return single_POST(post_slug)

@user_bp.route('/404')
def page_not_found():
    return render_template('404.html'), 404

@user_bp.route('/admin-dashboard')
@login_required
def admin_dashboard():
    return admin_user_dashboard()

@user_bp.route('/all-blogs' , methods=["GET","POST"])
def all_blogs():
    return all_blogs_details()

@user_bp.route('/add-blogs', methods=["GET","POST"])
def add_blogs():
    return add_blogs_details()

@user_bp.route('/my-blogs', methods=["GET","POST"])
def my_blogs():
    return my_blogs_details()


@user_bp.route('/update-blog/<int:id>', methods=["GET","POST"])
def update_blog(id):
    return update_specific_blog(id)

templates/about.html
{% extends 'header-footer.html'%}

{% block body %}
<!-- Page Header-->
        <header class="masthead" style="background-image: url('{{url_for('static', filename='img/about-bg.jpg')}}')">
            <div class="container position-relative px-4 px-lg-5">
                <div class="row gx-4 gx-lg-5 justify-content-center">
                    <div class="col-md-10 col-lg-8 col-xl-7">
                        <div class="page-heading">
                            <h1>About Me</h1>
                            <span class="subheading">This is what I do.</span>
                        </div>
                    </div>
                </div>
            </div>
        </header>
        <!-- Main Content-->
        <main class="mb-4">
            <div class="container px-4 px-lg-5">
                <div class="row gx-4 gx-lg-5 justify-content-center">
                    <div class="col-md-10 col-lg-8 col-xl-7">
                        <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Saepe nostrum ullam eveniet pariatur voluptates odit, fuga atque ea nobis sit soluta odio, adipisci quas excepturi maxime quae totam ducimus consectetur?</p>
                        <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Eius praesentium recusandae illo eaque architecto error, repellendus iusto reprehenderit, doloribus, minus sunt. Numquam at quae voluptatum in officia voluptas voluptatibus, minus!</p>
                        <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Aut consequuntur magnam, excepturi aliquid ex itaque esse est vero natus quae optio aperiam soluta voluptatibus corporis atque iste neque sit tempora!</p>
                    </div>
                </div>
            </div>
        </main>
        <!-- Footer-->
{% endblock%}

templates/add-post.html
{% extends 'header-footer.html'%}

{% block body %}
<link href="{{ url_for('static', filename='assets/css/main.css')}}" rel="stylesheet" type="text/css" />
<!-- Page Header-->
        <header class="masthead" style="background-image: url('{{url_for('static', filename='img/home-bg.jpg')}}')">
            <div class="container position-relative px-4 px-lg-5">
                <div class="row gx-4 gx-lg-5 justify-content-center">
                    <div class="col-md-10 col-lg-8 col-xl-7">
                        <div class="site-heading">
                            <h1>dashboard</h1>
                        </div>
                    </div>
                </div>
            </div>
        </header>
<section class="content-main">
    <form method="post" action="/add-post" enctype="multipart/form-data">
        {{form_blogs.hidden_tag()}}
            <div class="row">
                <div class="col-12">
                    {% if get_flashed_messages() %}
                        {% for message in get_flashed_messages(with_categories=true) %}
                            <div class="alert alert-{{ message[0] }}" role="alert">
                                {{ message[1] }}
                            </div>
                        {% endfor %}
                      {% endif %}
                    <div class="content-header">
                        <h2 class="content-title">Add New Blog</h2>
                        <div>
                            <button class="btn btn-light rounded font-sm mr-5 text-body hover-up" disabled>Save to draft</button>
                            {{form_blogs.submit()}}
                        </div>
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="col-lg-12">
                    <div class="card mb-4">
                        <div class="card-body">

                                <div class="row">
                                    <div class="col-md-3">
                                        <h6>1. General info</h6>
                                    </div>
                                    <div class="col-md-9">
                                        <div class="mb-4">
                                            <label class="form-label">Blog title</label>
                                            {{form_blogs.Blog_title}}
                                            {% for error in form_blogs.Blog_title.errors %}
                                                <span style="color: red;">{{ error }}</span>
                                            {% endfor %}
                                        </div>
                                        <div class="mb-4">
                                            <label class="form-label">Description</label>
                                            {{form_blogs.Description }}
                                            {% for error in form_blogs.Description.errors %}
                                                <span style="color: red;">{{ error }}</span>
                                            {% endfor %}
                                        </div>
                                    </div> <!-- col.// -->
                                </div> <!-- row.// -->
                                <div class="row">
                                    <div class="col-md-3">
                                        <h6>4. Media</h6>
                                    </div>
                                    <div class="col-md-9">
                                        <div class="mb-4">
                                            <label class="form-label">Images</label>
                                            {{form_blogs.file_field}}
<!--                                            <input class="form-control" type="file">-->
                                        </div>
                                    </div> <!-- col.// -->
                                </div> <!-- .row end// -->

                        </div>
                    </div>
                </div>
            </div>
        </form>
        </section> <!-- content-main end// -->
{% endblock%}

templates/contact.html
{% extends 'header-footer.html'%}

{% block body %}
        <!-- Page Header-->
        <header class="masthead" style="background-image: url('{{url_for('static', filename='img/contact-bg.jpg')}}')">
            <div class="container position-relative px-4 px-lg-5">
                <div class="row gx-4 gx-lg-5 justify-content-center">
                    <div class="col-md-10 col-lg-8 col-xl-7">
                        <div class="page-heading">
                            <h1>Contact Me</h1>
                            <span class="subheading">Have questions? I have answers.</span>
                        </div>
                    </div>
                </div>
            </div>
        </header>
        <!-- Main Content-->
        <main class="mb-4">
            <div class="container px-4 px-lg-5">
                <div class="row gx-4 gx-lg-5 justify-content-center">
                    <div class="col-md-10 col-lg-8 col-xl-7">
                        <p>Want to get in touch? Fill out the form below to send me a message and I will get back to you as soon as possible!</p>
                        <div class="my-5">
                            <!-- * * * * * * * * * * * * * * *-->
                            <!-- * * SB Forms Contact Form * *-->
                            <!-- * * * * * * * * * * * * * * *-->
                            <!-- This form is pre-integrated with SB Forms.-->
                            <!-- To make this form functional, sign up at-->
                            <!-- https://startbootstrap.com/solution/contact-forms-->
                            <!-- to get an API token!-->
                            <form id="contactForm" data-sb-form-api-token="API_TOKEN" method="POST" action="/contact-us">
                                <div class="form-floating">
                                    <input required name="name" class="form-control" id="name" type="text" placeholder="Enter your name..." data-sb-validations="required" />
                                    <label for="name">Name</label>
                                    <div class="invalid-feedback" data-sb-feedback="name:required">A name is required.</div>
                                </div>
                                <div class="form-floating">
                                    <input required name="email" class="form-control" id="email" type="email" placeholder="Enter your email..." data-sb-validations="required,email" />
                                    <label for="email">Email address</label>
                                    <div class="invalid-feedback" data-sb-feedback="email:required">An email is required.</div>
                                    <div class="invalid-feedback" data-sb-feedback="email:email">Email is not valid.</div>
                                </div>
                                <div class="form-floating">
                                    <input required name="phone_number" class="form-control" id="phone" type="tel" placeholder="Enter your phone number..." data-sb-validations="required" />
                                    <label for="phone">Phone Number</label>
                                    <div class="invalid-feedback" data-sb-feedback="phone:required">A phone number is required.</div>
                                </div>
                                <div class="form-floating">
                                    <textarea name="message" class="form-control" id="message" placeholder="Enter your message here..." style="height: 12rem" data-sb-validations="required"></textarea>
                                    <label for="message">Message</label>
                                    <div class="invalid-feedback" data-sb-feedback="message:required">A message is required.</div>
                                </div>
                                <br />
                                <!-- Submit success message-->
                                <!---->
                                <!-- This is what your users will see when the form-->
                                <!-- has successfully submitted-->
                                <div class="d-none" id="submitSuccessMessage">
                                    <div class="text-center mb-3">
                                        <div class="fw-bolder">Form submission successful!</div>
                                        To activate this form, sign up at
                                        <br />
                                        <a href="https://startbootstrap.com/solution/contact-forms">https://startbootstrap.com/solution/contact-forms</a>
                                    </div>
                                </div>
                                <!-- Submit error message-->
                                <!---->
                                <!-- This is what your users will see when there is-->
                                <!-- an error submitting the form-->
                                <div class="d-none" id="submitErrorMessage"><div class="text-center text-danger mb-3">Error sending message!</div></div>
                                <!-- Submit Button-->
                                <button class="btn btn-primary text-uppercase" id="submitButton" type="submit">Send</button>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </main>
        <!-- Footer-->
       {% endblock%}

templates/dashboard.html
{% extends 'header-footer.html'%}

{% block body %}
        <!-- Page Header-->
        <header class="masthead" style="background-image: url('{{url_for('static', filename='img/home-bg.jpg')}}')">
            <div class="container position-relative px-4 px-lg-5">
                <div class="row gx-4 gx-lg-5 justify-content-center">
                    <div class="col-md-10 col-lg-8 col-xl-7">
                        <div class="site-heading">
                            <h1>dashboard</h1>
                        </div>
                    </div>
                </div>
            </div>
        </header>
        <!-- Main Content-->
        <div class="container px-4 px-lg-5">
            <div class="row gx-4 gx-lg-5 justify-content-center">
                <div class="col-md-12 col-lg-12 col-xl-12">
                    {% if get_flashed_messages() %}
                            {% for message in get_flashed_messages() %}
                               <div class="alert alert-success" role="alert">
                                  {{ message }}
                               </div>
                            {% endfor %}
                      {% endif %}
                    <table class="table table-hover table-responsive">
                      <thead>
                        <tr>
                          <th scope="col">#</th>
                          <th scope="col">Name</th>
                          <th scope="col">post content</th>
                          <th scope="col">Date</th>
                          <th scope="col">slug</th>
                          <th scope="col">img file</th>
                          <th scope="col">auther ID</th>
                        </tr>
                      </thead>
                      <tbody>
                      {% for post in get_post %}
                            <tr>
                              <th scope="row">{{post.id}}</th>
                              <td>{{post.post_name}}</td>
                              <td>{{post.post_content[0:50]}}</td>
                              <td>{{formatted_date}}</td>
                              <td><a href="/post/{{post.slug}}">{{post.slug}}</a></td>
                              {% set image_link = url_for('static', filename='img/'+post.img_file) -%}
                              <td><img src="{{image_link}}"/></td>
                              <td>{{ post.user_posted }}</td>
                              <td><a href="javascript:void(0);"><i class="fa-solid fa-trash"></i></a></td>
                            </tr>
                      {% endfor %}
                      </tbody>
                    </table>
                </div>
            </div>
        </div>

{% endblock%}

templates/header-footer.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
        <meta name="description" content="" />
        <meta name="author" content="" />
        <title>Blog Post</title>
        <link rel="icon" type="image/x-icon" href="{{ url_for('static', filename='favicon.ico')}}" />
        <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.7.1/jquery.min.js" integrity="sha512-v2CJ7UaYy4JwqLDIrZUI/4hqeoQieOmAZNXBeQyjo21dadnwR+8ZaIJVT8EE2iyI61OV8e6M8PP2/4hpQINQ/g==" crossorigin="anonymous" referrerpolicy="no-referrer"></script>
        <!-- Font Awesome icons (free version)-->
        <script src="https://use.fontawesome.com/releases/v6.3.0/js/all.js" crossorigin="anonymous"></script>
        <!-- Google fonts-->
        <link href="https://fonts.googleapis.com/css?family=Lora:400,700,400italic,700italic" rel="stylesheet" type="text/css" />
        <link href="https://fonts.googleapis.com/css?family=Open+Sans:300italic,400italic,600italic,700italic,800italic,400,300,600,700,800" rel="stylesheet" type="text/css" />
        <!-- Core theme CSS (includes Bootstrap)-->
        <link href="{{ url_for('static', filename='css/styles.css')}}" rel="stylesheet" />
    </head>
    <body>
        <!-- Navigation-->
        <nav class="navbar navbar-expand-lg navbar-light" id="mainNav">
            <div class="container px-4 px-lg-5">
                <a class="navbar-brand" href="/">Start Bootstrap</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
                    Menu
                    <i class="fas fa-bars"></i>
                </button>
                <div class="collapse navbar-collapse" id="navbarResponsive">
                    <ul class="navbar-nav ms-auto py-4 py-lg-0">
                        <li class="nav-item"><a class="nav-link px-lg-3 py-3 py-lg-4" href="/">Home</a></li>
                        <li class="nav-item"><a class="nav-link px-lg-3 py-3 py-lg-4" href="/about">About</a></li>
                        <li class="nav-item"><a class="nav-link px-lg-3 py-3 py-lg-4" href="/post">Sample Post</a></li>
                        <li class="nav-item"><a class="nav-link px-lg-3 py-3 py-lg-4" href="/contact-us">Contact</a></li>
                        {% if current_user.is_authenticated %}
                            <li class="nav-item">
                                <a class="nav-link px-lg-3 py-3 py-lg-4" href="{{ url_for('user_bp.dashboard') }}">Account</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link px-lg-3 py-3 py-lg-4" href="{{ url_for('user_bp.logout') }}">Logout {{current_user.name}}</a>
                            </li>
                        {%else%}
                            <li class="nav-item">
                                <a class="nav-link px-lg-3 py-3 py-lg-4" href="{{ url_for('user_bp.login') }}">Login</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link px-lg-3 py-3 py-lg-4" href="{{ url_for('user_bp.register') }}">Sign Up</a>
                            </li>
                        {%endif%}
                    </ul>
                </div>
            </div>
        </nav>
        <!-- Page Header-->
        {% block body %} {% endblock %}
        <!-- Footer-->
        <footer class="border-top">
            <div class="container px-4 px-lg-5">
                <div class="row gx-4 gx-lg-5 justify-content-center">
                    <div class="col-md-10 col-lg-8 col-xl-7">
                        <ul class="list-inline text-center">
                            <li class="list-inline-item">
                                <a href="javascript:void(0);">
                                    <span class="fa-stack fa-lg">
                                        <i class="fas fa-circle fa-stack-2x"></i>
                                        <i class="fab fa-twitter fa-stack-1x fa-inverse"></i>
                                    </span>
                                </a>
                            </li>
                            <li class="list-inline-item">
                                <a href="javascript:void(0);" target="_blank">
                                    <span class="fa-stack fa-lg">
                                        <i class="fas fa-circle fa-stack-2x"></i>
                                        <i class="fab fa-facebook-f fa-stack-1x fa-inverse"></i>
                                    </span>
                                </a>
                            </li>
                            <li class="list-inline-item">
                                <a href="javascript:void(0);" target="_blank">
                                    <span class="fa-stack fa-lg">
                                        <i class="fas fa-circle fa-stack-2x"></i>
                                        <i class="fab fa-github fa-stack-1x fa-inverse"></i>
                                    </span>
                                </a>
                            </li>
                        </ul>
                        <div class="small text-center text-muted fst-italic">Copyright &copy; Your Website 2024</div>
                    </div>
                </div>
            </div>
        </footer>
        <!-- Bootstrap core JS-->
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js"></script>
        <!-- Core theme JS-->
        <script src="{{url_for('static', filename='js/scripts.js')}}"></script>
    </body>
</html>

templates/index.html
{% extends 'header-footer.html'%}

{% block body %}
        <!-- Page Header-->
        <header class="masthead" style="background-image: url('{{url_for('static', filename='img/home-bg.jpg')}}')">
            <div class="container position-relative px-4 px-lg-5">
                <div class="row gx-4 gx-lg-5 justify-content-center">
                    <div class="col-md-10 col-lg-8 col-xl-7">
                        <div class="site-heading">
                            <h1>Clean Blog</h1>
                            <span class="subheading">A Blog Theme by Start Bootstrap</span>
                        </div>
                    </div>
                </div>
            </div>
        </header>
        <!-- Main Content-->
        <div class="container px-4 px-lg-5">
            <div class="row gx-4 gx-lg-5 justify-content-center">
                <div class="col-md-10 col-lg-8 col-xl-7">
                    <!-- Post preview-->
                    {% for posts, formatted_date in post %}
                        <div class="post-preview">
                            <a href="/post/{{posts.slug}}">
                                <h2 class="post-title">{{posts.post_name}}</h2>
                                <p class="post-subtitle">{{posts.post_content[0:130]}}</p>
                            </a>
                            <p class="post-meta">
                                Posted by
                                <a href="#!">admin</a>
                                {{formatted_date}}
                            </p>
                        </div>
                    {%endfor%}
                    <!-- Divider-->
                    <hr class="my-4" />
                    <!-- Pager-->
                    <div class="d-flex justify-content-end mb-4"><a class="btn btn-primary text-uppercase" href="#!">Older Posts →</a></div>
                </div>
            </div>
        </div>

{% endblock%}

templates/login.html
{% extends 'header-footer.html'%}

{% block body %}
        <header class="masthead" style="background-image: url('{{url_for('static', filename='img/home-bg.jpg')}}')">
            <div class="container position-relative px-4 px-lg-5">
                <div class="row gx-4 gx-lg-5 justify-content-center">
                    <div class="col-md-10 col-lg-8 col-xl-7">
                        <div class="site-heading">
                            <h1>login</h1>
                        </div>
                    </div>
                </div>
            </div>
        </header>

      <div class="container">
        <div class="row">
          <div class="col-md-12 col-sm-12">
              {% if get_flashed_messages() %}
                {% for message in get_flashed_messages(with_categories=true) %}
                    <div class="alert alert-{{ message[0] }}" role="alert">
                        {{ message[1] }}
                    </div>
                {% endfor %}
              {% endif %}
            <form class="form-signin" method="POST" action="">
                {{form.hidden_tag()}}
              <img class="mb-4" src="https://getbootstrap.com/docs/4.0/assets/brand/bootstrap-solid.svg" alt="" width="72" height="72">
              <h1 class="h3 mb-3 font-weight-normal">Please sign in</h1>
              <label type="email" class="sr-only">username</label>
              {{form.email()}}
              <label type="password" class="sr-only">Password</label>
              {{form.password()}}
              <div class="checkbox mb-3">
                <label>
                  <input type="checkbox" value="remember-me"> Remember me
                </label>
              </div>
              {{form.submit()}}
                <div class="register">
                    <p>Don't have an account? <a href="{{url_for('user_bp.register')}}">Sign up</a></p>
                </div>
          </form>
          </div>
        </div>
      </div>

{% endblock %}

templates/update-post.html
{% extends 'header-footer.html'%}

{% block body %}
<link href="{{ url_for('static', filename='assets/css/main.css')}}" rel="stylesheet" type="text/css" />
<!-- Page Header-->
        <header class="masthead" style="background-image: url('{{url_for('static', filename='img/home-bg.jpg')}}')">
            <div class="container position-relative px-4 px-lg-5">
                <div class="row gx-4 gx-lg-5 justify-content-center">
                    <div class="col-md-10 col-lg-8 col-xl-7">
                        <div class="site-heading">
                            <h1>Update Post</h1>
                        </div>
                    </div>
                </div>
            </div>
        </header>
<section class="content-main">
    <form method="POST" action="/user/update-post/{{post.user_posted}}/{{post.id}}" enctype="multipart/form-data">
<!--        <a href="/user/update-post/{{post.id}}">click</a>-->
        {{form_blogs.hidden_tag()}}
            <div class="row">
                <div class="col-12">
                    {% if get_flashed_messages() %}
                        {% for message in get_flashed_messages(with_categories=true) %}
                            <div class="alert alert-{{ message[0] }}" role="alert">
                                {{ message[1] }}
                            </div>
                        {% endfor %}
                      {% endif %}
                    <div class="content-header">
                        <h2 class="content-title">Update Post</h2>
                        <div>
                            <button class="btn btn-light rounded font-sm mr-5 text-body hover-up" disabled>Save to draft</button>
                            {% if not_found_url %}
                                <a href="{{ url_for('user_bp.dashboard') }}">Cant Find Any Thing</a>
                            {% else %}
                                {{form_blogs.submit()}}
                            {% endif %}
                        </div>
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="col-lg-12">
                    <div class="card mb-4">
                        <div class="card-body">

                                <div class="row">
                                    <div class="col-md-3">
                                        <h6>1. General info</h6>
                                    </div>
                                    <div class="col-md-9">
                                        <div class="mb-4">
                                            <label class="form-label">Blog title</label>
                                            {{form_blogs.Blog_title(value = post.post_name)}}
                                            {% for error in form_blogs.Blog_title.errors %}
                                                <span style="color: red;">{{ error }}</span>
                                            {% endfor %}
                                        </div>
                                        <div class="mb-4">
                                            <label class="form-label">Description</label>
                                            <textarea class="form-control" id="Description" name="Description" placeholder="Type here" required="">{{post.post_content }}</textarea>
                                            {% for error in form_blogs.Description.errors %}
                                                <span style="color: red;">{{ error }}</span>
                                            {% endfor %}
                                        </div>
                                    </div> <!-- col.// -->
                                </div> <!-- row.// -->
                                <div class="row">
                                    <div class="col-md-3">
                                        <h6>4. Media</h6>
                                    </div>
                                    <div class="col-md-9">
                                        <div class="mb-4">
                                            <label class="form-label">Images</label>
                                            {{form_blogs.file_field}}
                                        </div>
                                    </div> <!-- col.// -->
                                </div> <!-- .row end// -->

                        </div>
                    </div>
                </div>
            </div>
        </form>
        </section> <!-- content-main end// -->
{% endblock%}