routes/user_bp.py
from flask import Blueprint, render_template, redirect, url_for, flash
from flask_login import login_required, current_user, logout_user
from functools import wraps

user_bp = Blueprint('user_bp', __name__)

from controllers.UserController import home_page, dashboard_details, about_details, post_page, contact_page, single_POST, admin_user_dashboard, all_blogs_details, add_blogs_details, my_blogs_details, update_specific_blog
from controllers.auth_controller import login_check, register_check



@user_bp.route('/')
def home():
    return home_page()


@user_bp.route('/login', methods=["GET", "POST"])
def login():
    validate_data = login_check()
    if not validate_data:
        flash("User Doesn't Exists!!")
    return validate_data


@user_bp.route('/logout')
@login_required
def logout():
    logout_user()
    return redirect(url_for('user_bp.home'))

@user_bp.route('/register', methods=['GET', 'POST'])
def register():
    validate_data = register_check()
    return validate_data


@user_bp.route('/dashboard')
@login_required
def dashboard():
    dashboard  = dashboard_details()
    return dashboard


# NORMAL PAGES ROUTE STARTS HERE

@user_bp.route('/about')
def about():
    return about_details()

@user_bp.route('/post')
def posts():
    return post_page()


@user_bp.route('/contact-us' , methods=["GET","POST"])
def contact_us():
    return contact_page()


@user_bp.route('/post/<string:post_slug>', methods=["GET","POST"])
def sinlge_post(post_slug):
    return single_POST(post_slug)

@user_bp.route('/404')
def page_not_found():
    return render_template('404.html'), 404

@user_bp.route('/admin-dashboard')
@login_required
def admin_dashboard():
    return admin_user_dashboard()

@user_bp.route('/all-blogs' , methods=["GET","POST"])
def all_blogs():
    return all_blogs_details()

@user_bp.route('/add-blogs', methods=["GET","POST"])
def add_blogs():
    return add_blogs_details()

@user_bp.route('/my-blogs', methods=["GET","POST"])
def my_blogs():
    return my_blogs_details()


@user_bp.route('/update-blog/<int:id>', methods=["GET","POST"])
def update_blog(id):
    return update_specific_blog(id)

templates/admin-dashboard/add-post.html
{% extends 'admin-dashboard/header-footer-admin.html'%}

{% block body %}
<section class="content-main">
    <form method="post" action="/add-blogs">
        {{form_blogs.hidden_tag()}}
            <div class="row">
                <div class="col-6">
                    {% if get_flashed_messages() %}
                        {% for message in get_flashed_messages(with_categories=true) %}
                            <div class="alert alert-{{ message[0] }}" role="alert">
                                {{ message[1] }}
                            </div>
                        {% endfor %}
                      {% endif %}
                    <div class="content-header">
                        <h2 class="content-title">Add New Blog</h2>
                        <div>
                            <button class="btn btn-light rounded font-sm mr-5 text-body hover-up">Save to draft</button>
                            {{form_blogs.submit()}}
                        </div>
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="col-lg-6">
                    <div class="card mb-4">
                        <div class="card-body">

                                <div class="row">
                                    <div class="col-md-3">
                                        <h6>1. General info</h6>
                                    </div>
                                    <div class="col-md-9">
                                        <div class="mb-4">
                                            <label class="form-label">Blog title</label>
                                            {{form_blogs.Blog_title}}
                                            {% for error in form_blogs.Blog_title.errors %}
                                                <span style="color: red;">{{ error }}</span>
                                            {% endfor %}
                                        </div>
                                        <div class="mb-4">
                                            <label class="form-label">Description</label>
                                            {{form_blogs.Description }}
                                            {% for error in form_blogs.Description.errors %}
                                                <span style="color: red;">{{ error }}</span>
                                            {% endfor %}
                                        </div>
                                    </div> <!-- col.// -->
                                </div> <!-- row.// -->
                                <div class="row">
                                    <div class="col-md-3">
                                        <h6>4. Media</h6>
                                    </div>
                                    <div class="col-md-9">
                                        <div class="mb-4">
                                            <label class="form-label">Images</label>
                                            <input class="form-control" type="file">
                                        </div>
                                    </div> <!-- col.// -->
                                </div> <!-- .row end// -->

                        </div>
                    </div>
                </div>
            </div>
        </form>
        </section> <!-- content-main end// -->
{% endblock%}

templates/admin-dashboard/all-blogs.html
{% extends 'admin-dashboard/header-footer-admin.html'%}

{% block body %}
 <section class="content-main">
                        {% if get_flashed_messages() %}
                            {% for message in get_flashed_messages(with_categories=true) %}
                                <div class="alert alert-{{ message[0] }}" role="alert">
                                    {{ message[1] }}
                                </div>
                            {% endfor %}
                          {% endif %}
                <div class="content-header">
                    <div>
                        <h2 class="content-title card-title">All Blogs</h2>
                        <p>Lorem ipsum dolor sit amet.</p>
                    </div>
                    <div>
                        <a href="#" class="btn btn-light rounded font-md">Export</a>
                        <a href="#" class="btn btn-light rounded font-md">Import</a>
                        <a href="{{url_for('user_bp.add_blogs')}}" class="btn btn-primary btn-sm rounded">Create new</a>
                    </div>
                </div>
                <div class="card mb-4">
                    <header class="card-header">
                        <div class="row align-items-center">
                            <div class="col col-check flex-grow-0">
                                <div class="form-check ms-2">
                                    <input class="form-check-input" type="checkbox" value="" />
                                </div>
                            </div>
                            <div class="col-md-3 col-12 me-auto mb-md-0 mb-3">
                                <select class="form-select">
                                    <option selected>All category</option>
                                    <option>Electronics</option>
                                    <option>Clothes</option>
                                    <option>Automobile</option>
                                </select>
                            </div>
                            <div class="col-md-2 col-6">
                                <input type="date" value="02.05.2021" class="form-control" />
                            </div>
                            <div class="col-md-2 col-6">
                                <select class="form-select">
                                    <option selected>Status</option>
                                    <option>Active</option>
                                    <option>Disabled</option>
                                    <option>Show all</option>
                                </select>
                            </div>
                        </div>
                    </header>
                    <!-- card-header end// -->
                    <div class="card-body">
                        {% for post in for_date %}
                        <article class="itemlist">
                            <div class="row align-items-center">
                                <div class="col col-check flex-grow-0">
                                    <div class="form-check">
                                        <input class="form-check-input" type="checkbox" />
                                    </div>
                                </div>
                                <div class="col-lg-2 col-sm-4 col-2 flex-grow-2 col-name">
                                    <a class="itemside" href="post/{{post.slug}}" target="_blank">
                                        <div class="left">
                                            {% set image_link = url_for('static', filename='img/'+post.img_file) -%}
                                            <img src="{{image_link}}" class="img-sm img-thumbnail" alt="Item" />
                                        </div>
                                        <div class="info">
                                            <h6 class="mb-0">{{post.post_name}}</h6>
                                        </div>
                                    </a>
                                </div>
                                <div class="col-lg-4 col-sm-2 col-4 col-price"><p>{{post.post_content[0:150]}}...</p></div>
                                <div class="col-lg-1 col-sm-2 col-4 col-status">
                                    {% if post.status == "published" %}
                                        <span class="badge rounded-pill alert-success">{{ post.status }}</span>
                                    {% else %}
                                        <span class="badge rounded-pill alert-danger">{{ post.status }}</span>
                                    {% endif %}
                                </div>
                                <div class="col-lg-2 col-sm-2 col-4 col-date">
                                    <span>{{formatted_posts}}</span>
                                </div>
                                <div class="col-lg-2 col-sm-2 col-4 col-action text-end d-flex align-items-center justify-content-between">
                                     <a href="#" class="btn btn-sm font-sm rounded btn-brand"> <i class="material-icons md-edit"></i> Edit </a>
                                    <form action="/all-blogs" method="post">
                                        <input type="hidden" name="post_id" value="{{post.id}}">
                                        {{ delete_form.hidden_tag()}}
<!--                                        {{delete_form.delete()}}-->
                                        <button type="submit" class="btn btn-sm font-sm btn-light rounded"> <i class="material-icons md-delete_forever"></i> Delete </button>
                                    </form>
                                </div>
                            </div>
                            <!-- row .// -->
                        </article>
                        {% endfor%}
                        <!-- itemlist  .// -->
                    </div>
                    <!-- card-body end// -->
                </div>
                <!-- card end// -->
                <div class="pagination-area mt-30 mb-50">
                    <nav aria-label="Page navigation example">
                        <ul class="pagination justify-content-start">
                            <li class="page-item active"><a class="page-link" href="#">01</a></li>
                            <li class="page-item"><a class="page-link" href="#">02</a></li>
                            <li class="page-item"><a class="page-link" href="#">03</a></li>
                            <li class="page-item"><a class="page-link dot" href="#">...</a></li>
                            <li class="page-item"><a class="page-link" href="#">16</a></li>
                            <li class="page-item">
                                <a class="page-link" href="#"><i class="material-icons md-chevron_right"></i></a>
                            </li>
                        </ul>
                    </nav>
                </div>
            </section>
            <!-- content-main end// -->

{% endblock%}

templates/admin-dashboard/header-footer-admin.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8" />
        <title>{{current_user.name}} Dashboard</title>
        <meta http-equiv="x-ua-compatible" content="ie=edge" />
        <meta name="description" content="" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <meta property="og:title" content="" />
        <meta property="og:type" content="" />
        <meta property="og:url" content="" />
        <meta property="og:image" content="" />
        <!-- Favicon -->
        <link rel="shortcut icon" type="image/x-icon" href="{{ url_for('static', filename='assets/imgs/theme/favicon.svg')}}" />
        <!-- Template CSS -->
        <link href="{{ url_for('static', filename='assets/css/main.css')}}" rel="stylesheet" type="text/css" />
    </head>

    <body>
        <div class="screen-overlay"></div>
        <aside class="navbar-aside" id="offcanvas_aside">
            <div class="aside-top">
                <a href="/" class="brand-wrap">
                    <img src="{{ url_for('static', filename='assets/imgs/theme/logo.svg')}}" class="logo" alt="Nest Dashboard" />
                </a>
                <div>
                    <button class="btn btn-icon btn-aside-minimize"><i class="text-muted material-icons md-menu_open"></i></button>
                </div>
            </div>
            <nav>
                <ul class="menu-aside">
                    <li class="menu-item active">
                        <a class="menu-link" href="{{ url_for('user_bp.admin_dashboard') }}">
                            <i class="icon material-icons md-home"></i>
                            <span class="text">Dashboard</span>
                        </a>
                    </li>
                    <li class="menu-item has-submenu">
                        <a class="menu-link" href="javascript:void(0);">
                            <i class="icon material-icons md-shopping_bag"></i>
                            <span class="text">Blogs</span>
                        </a>
                        <div class="submenu">
                            <a href="{{ url_for('user_bp.all_blogs') }}">All Blogs</a>
                            <a href="{{ url_for('user_bp.my_blogs') }}">My Blogs</a>
                            <a href="{{ url_for('user_bp.add_blogs') }}">Add Blogs</a>
                        </div>
                    </li>
                </ul>
                <hr />
                <br />
            </nav>
        </aside>

        <main class="main-wrap">
            <header class="main-header navbar">
                <div class="col-search">
                    <form class="searchform">
                        <div class="input-group">
                            <input list="search_terms" type="text" class="form-control" placeholder="Search term" />
                            <button class="btn btn-light bg" type="button"><i class="material-icons md-search"></i></button>
                        </div>
                        <datalist id="search_terms">
                            <option value="Products"></option>
                            <option value="New orders"></option>
                            <option value="Apple iphone"></option>
                            <option value="Ahmed Hassan"></option>
                        </datalist>
                    </form>
                </div>
                <div class="col-nav">
                    <button class="btn btn-icon btn-mobile me-auto" data-trigger="#offcanvas_aside"><i class="material-icons md-apps"></i></button>
                    <ul class="nav">
                        <li class="nav-item">
                            <a class="nav-link btn-icon" href="#">
                                <i class="material-icons md-notifications animation-shake"></i>
                                <span class="badge rounded-pill">3</span>
                            </a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link btn-icon darkmode" href="#"> <i class="material-icons md-nights_stay"></i> </a>
                        </li>
                        <li class="nav-item">
                            <a href="#" class="requestfullscreen nav-link btn-icon"><i class="material-icons md-cast"></i></a>
                        </li>
                        <li class="dropdown nav-item">
                            <a class="dropdown-toggle" data-bs-toggle="dropdown" href="#" id="dropdownLanguage" aria-expanded="false"><i class="material-icons md-public"></i></a>
                            <div class="dropdown-menu dropdown-menu-end" aria-labelledby="dropdownLanguage">
                                <a class="dropdown-item text-brand" href="#"><img src="assets/imgs/theme/flag-us.png" alt="English" />English</a>
                                <a class="dropdown-item" href="#"><img src="{{ url_for('static', filename='assets/imgs/theme/flag-fr.png')}}" alt="Français" />Français</a>
                                <a class="dropdown-item" href="#"><img src="{{ url_for('static', filename='assets/imgs/theme/flag-jp.png')}}" alt="Français" />日本語</a>
                                <a class="dropdown-item" href="#"><img src="{{ url_for('static', filename='assets/imgs/theme/flag-cn.png')}}" alt="Français" />中国人</a>
                            </div>
                        </li>
                        <li class="dropdown nav-item">
                            <a class="dropdown-toggle" data-bs-toggle="dropdown" href="#" id="dropdownAccount" aria-expanded="false"> <img class="img-xs rounded-circle" src="{{ url_for('static', filename='assets/imgs/people/avatar-2.png')}}" alt="User" /></a>
                            <div class="dropdown-menu dropdown-menu-end" aria-labelledby="dropdownAccount">
                                <a class="dropdown-item" href="#"><i class="material-icons md-perm_identity"></i>Edit Profile</a>
                                <a class="dropdown-item" href="#"><i class="material-icons md-settings"></i>Account Settings</a>
                                <a class="dropdown-item" href="#"><i class="material-icons md-account_balance_wallet"></i>Wallet</a>
                                <a class="dropdown-item" href="#"><i class="material-icons md-receipt"></i>Billing</a>
                                <a class="dropdown-item" href="#"><i class="material-icons md-help_outline"></i>Help center</a>
                                <div class="dropdown-divider"></div>
                                <a class="dropdown-item text-danger" href="{{ url_for('user_bp.logout') }}"><i class="material-icons md-exit_to_app"></i>Logout</a>
                            </div>
                        </li>
                    </ul>
                </div>
            </header>
            {% block body %} {% endblock %}
            <!-- content-main end// -->
            <footer class="main-footer font-xs">
                <div class="row pb-30 pt-15">
                    <div class="col-sm-6">
                        <script>
                            document.write(new Date().getFullYear());
                        </script>
                        &copy; Nest - HTML Ecommerce Template .
                    </div>
                    <div class="col-sm-6">
                        <div class="text-sm-end">All rights reserved</div>
                    </div>
                </div>
            </footer>
        </main>

        <script src="{{ url_for('static', filename='assets/js/vendors/jquery-3.6.0.min.js')}}"></script>
        <script src="{{ url_for('static', filename='assets/js/vendors/bootstrap.bundle.min.js')}}"></script>
        <script src="{{ url_for('static', filename='assets/js/vendors/select2.min.js')}}"></script>
        <script src="{{ url_for('static', filename='assets/js/vendors/perfect-scrollbar.js')}}"></script>
        <script src="{{ url_for('static', filename='assets/js/vendors/jquery.fullscreen.min.js')}}"></script>
        <script src="{{ url_for('static', filename='assets/js/vendors/chart.js')}}"></script>
        <!-- Main Script -->
        <script src="{{ url_for('static', filename='assets/js/main.js')}}" type="text/javascript"></script>
        <script src="{{ url_for('static', filename='assets/js/custom-chart.js')}}" type="text/javascript"></script>
    </body>
</html>

templates/admin-dashboard/my-blogs.html
{% extends 'admin-dashboard/header-footer-admin.html'%}

{% block body %}
 <section class="content-main">
                <div class="content-header">
                    <div>
                        <h2 class="content-title card-title">All Blogs</h2>
                        <p>Lorem ipsum dolor sit amet.</p>
                    </div>
                    <div>
                        <a href="#" class="btn btn-light rounded font-md">Export</a>
                        <a href="#" class="btn btn-light rounded font-md">Import</a>
                        <a href="{{url_for('user_bp.add_blogs')}}" class="btn btn-primary btn-sm rounded">Create new</a>
                    </div>
                </div>
                <div class="card mb-4">
                    <header class="card-header">
                        <div class="row align-items-center">
                            <div class="col col-check flex-grow-0">
                                <div class="form-check ms-2">
                                    <input class="form-check-input" type="checkbox" value="" />
                                </div>
                            </div>
                            <div class="col-md-3 col-12 me-auto mb-md-0 mb-3">
                                <select class="form-select">
                                    <option selected>All category</option>
                                    <option>Electronics</option>
                                    <option>Clothes</option>
                                    <option>Automobile</option>
                                </select>
                            </div>
                            <div class="col-md-2 col-6">
                                <input type="date" value="02.05.2021" class="form-control" />
                            </div>
                            <div class="col-md-2 col-6">
                                <select class="form-select">
                                    <option selected>Status</option>
                                    <option>Active</option>
                                    <option>Disabled</option>
                                    <option>Show all</option>
                                </select>
                            </div>
                        </div>
                    </header>
                    <!-- card-header end// -->
                    <div class="card-body">
                        {% for post in for_date %}
                        <article class="itemlist">
                            <div class="row align-items-center">
                                <div class="col col-check flex-grow-0">
                                    <div class="form-check">
                                        <input class="form-check-input" type="checkbox" />
                                    </div>
                                </div>
                                <div class="col-lg-2 col-sm-4 col-2 flex-grow-2 col-name">
                                    <a class="itemside" href="post/{{post.slug}}" target="_blank">
                                        <div class="left">
                                            {% set image_link = url_for('static', filename='img/'+post.img_file) -%}
                                            <img src="{{image_link}}" class="img-sm img-thumbnail" alt="Item" />
                                        </div>
                                        <div class="info">
                                            <h6 class="mb-0">{{post.post_name}}</h6>
                                        </div>
                                    </a>
                                </div>
                                <div class="col-lg-4 col-sm-2 col-4 col-price"><p>{{post.post_content[0:150]}}...</p></div>
                                <div class="col-lg-1 col-sm-2 col-4 col-status">
                                   {% if post.status == "published" %}
                                        <span class="badge rounded-pill alert-success">{{ post.status }}</span>
                                    {% else %}
                                        <span class="badge rounded-pill alert-danger">{{ post.status }}</span>
                                    {% endif %}
                                </div>
                                <div class="col-lg-2 col-sm-2 col-4 col-date">
                                    <span>{{formatted_posts}}</span>
                                </div>
                                <div class="col-lg-2 col-sm-2 col-4 col-action text-end d-flex align-items-center justify-content-between">
                                    <a href="#" class="btn btn-sm font-sm rounded btn-brand"> <i class="material-icons md-edit"></i> Edit </a>
                                    <form action="/all-blogs" method="post">
                                        <input type="hidden" name="post_id" value="{{post.id}}">
                                        {{ delete_form.hidden_tag()}}
<!--                                        {{delete_form.delete()}}-->
                                        <button type="submit" class="btn btn-sm font-sm btn-light rounded"> <i class="material-icons md-delete_forever"></i> Delete </button>
                                    </form>
                                </div>
                            </div>
                            <!-- row .// -->
                        </article>
                        {% endfor%}
                        <!-- itemlist  .// -->
                    </div>
                    <!-- card-body end// -->
                </div>
                <!-- card end// -->
                <div class="pagination-area mt-30 mb-50">
                    <nav aria-label="Page navigation example">
                        <ul class="pagination justify-content-start">
                            <li class="page-item active"><a class="page-link" href="#">01</a></li>
                            <li class="page-item"><a class="page-link" href="#">02</a></li>
                            <li class="page-item"><a class="page-link" href="#">03</a></li>
                            <li class="page-item"><a class="page-link dot" href="#">...</a></li>
                            <li class="page-item"><a class="page-link" href="#">16</a></li>
                            <li class="page-item">
                                <a class="page-link" href="#"><i class="material-icons md-chevron_right"></i></a>
                            </li>
                        </ul>
                    </nav>
                </div>
            </section>
            <!-- content-main end// -->

{% endblock%}